### ISSUE TITLE
MediaPlayer: error (1, -2147483648) with Ti SDK 5.1.2 GA

### ISSUE THREAD

**Issue by AndrewNatoli** [DesktopSolutionsSoftware/android-audioplayer#4]
```
[ERROR] :  MediaPlayer: error (1, -2147483648)
[WARN] :   AdvancedAudioPlayer: (KrollRuntimeThread) [31665,112948] Issue while initializing :
[WARN] :   AdvancedAudioPlayer: java.io.IOException: Prepare failed.: status=0x1
[WARN] :   AdvancedAudioPlayer:  at android.media.MediaPlayer._prepare(Native Method)
[WARN] :   AdvancedAudioPlayer:  at android.media.MediaPlayer.prepare(MediaPlayer.java:1163)
[WARN] :   AdvancedAudioPlayer:  at com.kcwdev.audio.MediaPlayerWrapper.initialize(MediaPlayerWrapper.java:145)
[WARN] :   AdvancedAudioPlayer:  at com.kcwdev.audio.MediaPlayerWrapper.<init>(MediaPlayerWrapper.java:80)
[WARN] :   AdvancedAudioPlayer:  at com.kcwdev.audio.AudioPlayerProxy.getSound(AudioPlayerProxy.java:185)
[WARN] :   AdvancedAudioPlayer:  at com.kcwdev.audio.AudioPlayerProxy.getDuration(AudioPlayerProxy.java:109)
[WARN] :   AdvancedAudioPlayer:  at org.appcelerator.kroll.runtime.v8.V8Object.nativeCallProperty(Native Method)
[WARN] :   AdvancedAudioPlayer:  at org.appcelerator.kroll.runtime.v8.V8Object.callProperty(V8Object.java:73)
[WARN] :   AdvancedAudioPlayer:  at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1145)
[WARN] :   AdvancedAudioPlayer:  at android.os.Handler.dispatchMessage(Handler.java:98)
[WARN] :   AdvancedAudioPlayer:  at android.os.Looper.loop(Looper.java:148)
[WARN] :   AdvancedAudioPlayer:  at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[INFO] :   com.connectoncall.audioplayer > getAndroidMediaPlayer: typeof mediaPlayer = object
```

Media player takes close to a minute to appear then throws an error.

**Comment by AndrewNatoli** [comment]
Building an app with `TiSDK 5.2.0` seems to resolve this problem?
